language: python

env:
  - TOXENV=lint
  - TOXENV=py33-lint
  - TOXENV=docs
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py32
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=pypy

install: .travis/install.sh

script: .travis/run.sh

branches:
  only:
    - master
    - develop
    - /^[0-9]+\.[0-9]+\.[Xx]$/

notifications:
  irc:
    channels:
      - "irc.freenode.org#pypa-dev"
    use_notice: true
    skip_join: true
